name: YouTube
on:
  workflow_dispatch: {}
jobs:
  run:
    name: 実行
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install
      - run: node src/main.js
      - run: cat yt.txt
      - uses: actions/upload-artifact@v4
        with:
          name: video-url
          path: yt.txt
