name: YouTube
on:
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: node src/main.js
      - run: cat yt.txt
      - uses: actions/upload-artifact@v4
        with:
          name: video-url
          path: yt.txt